// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'Please add your GoogleService-Info.plist and reconfigure.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTGZgS7Lt34tdDK8JBf1CWi6Jofiw40yY',
    appId: '1:1057378791268:android:c9fb118a4d7fd54ccbd471',
    messagingSenderId: '1057378791268',
    projectId: 'placeofsales-realestate',
    storageBucket: 'placeofsales-realestate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7C26-H8mv7ahxKwpDobZkXWcrK6GVQn4',
    appId: '1:1057378791268:ios:5407f41aaa22b5adcbd471',
    messagingSenderId: '1057378791268',
    projectId: 'placeofsales-realestate',
    storageBucket: 'placeofsales-realestate.appspot.com',
    iosBundleId: 'com.avontra.propertify',
    iosClientId:
        '1057378791268-a3llhfurt8j5j8njk7tq0pc72v4iov3k.apps.googleusercontent.com',
  );
}
