part of 'admin_bloc.dart';

@Freezed()
class AdminState with _$AdminState {
  const factory AdminState({
    @Default(false) bool isLoading,
    List<UserModel>? users,
    List<PostAdModel>? postAds,
    List<BannerAdModel>? bannerAds,
    List<ProjectsAdminViewModel>? projects,
    List<CallbackRequestModel>? callbackRequests,
    List<VerificationRequestModel>? verificationRequests,
    List<HomeLoanModel>? homeLoans,
    List<InteriorDesignModel>? interiorDesigns,
    List<RequestModel>? requests,
    List<AdUserModel>? ads,
    List<ServicesResponseModel>? services,
    List<FeedPostsResponseModel>? properties,
    List<AdminCompanyModel>? companies,
    NotifyStatus? notifyStatus,
    @Default(1) int currentPage,
    @Default(1) int currentPostAdsPage,
    @Default(1) int currentBannerAdsPage,
    @Default(1) int currentProjectsPage,
    @Default(1) int currentCallbackRequestsPage,
    @Default(1) int currentVerificationRequestsPage,
    @Default(1) int currentHomeLoansPage,
    @Default(1) int currentInteriorDesignsPage,
    @Default(1) int currentRequestsPage,
    @Default(1) int currentAdsPage,
    @Default(1) int currentServicesPage,
    @Default(1) int currentPropertiesPage,
    @Default(1) int currentCompaniesPage,
    @Default(false) bool hasMore,
    @Default(false) bool hasMorePostAds,
    @Default(false) bool hasMoreBannerAds,
    @Default(false) bool hasMoreProjects,
    @Default(false) bool hasMoreCallbackRequests,
    @Default(false) bool hasMoreVerificationRequests,
    @Default(false) bool hasMoreHomeLoans,
    @Default(false) bool hasMoreInteriorDesigns,
    @Default(false) bool hasMoreRequests,
    @Default(false) bool hasMoreAds,
    @Default(false) bool hasMoreServices,
    @Default(false) bool hasMoreProperties,
    @Default(false) bool hasMoreCompanies,
    List<ReelResponseModel>? adminReels,
    @Default(1) int currentAdminReelsPage,
    @Default(false) bool hasMoreAdminReels,
    List<AdminCompanyModel>? gstPendingCompanies,
    @Default(1) int currentGstPendingPage,
    @Default(false) bool hasMoreGstPending,
  }) = _AdminState;
}
